server:
  port: 8001

spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    #失效时间，设置为lease-renewal-interval-in-seconds的3倍
    lease-expiration-duration-in-seconds: 15
    #心跳时间
    lease-renewal-interval-in-seconds: 5

ribbon:
  # 同一实例最大重试次数，不包括首次调用
  MaxAutoRetries: 0
  # 重试其他实例的最大重试次数，不包括首次所选的server
  MaxAutoRetriesNextServer: 1
  # 读超时时间
  ReadTimeout: 1000
  # 连接server时间
  ConnectTimeout: 1000
  #对所有操作都进行重试，默认是false
  OkToRetryOnAllOperations: false


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            # 默认1s
            timeoutInMilliseconds: 10000
  threadpool:
    default:
      #核心线程中，超过这个返回失败
      coreSize: 10



feign:
  hystrix:
    enabled: true
